/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AuthModealPage: typeof import('./src/components/AuthModealPage.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShortLinkCut: typeof import('./src/components/ShortLinkCut.vue')['default']
    ShortLinkList: typeof import('./src/components/ShortLinkList.vue')['default']
    ShortLinkPanel: typeof import('./src/components/ShortLinkPanel.vue')['default']
    ShortLinkSettings: typeof import('./src/components/ShortLinkCut.vue')['default']
  }
}
